import createConfig from '../../configuring/create.js';
import type { ExpandedConfig } from '../../configuring/types.js';
import type { RecordInput, RecordOutput } from '../../types/api.js';
import type { Step } from '../../types/api.js';

/**
 * Executes instrumented code and records the execution trace.
 *
 * This function is the third stage in the tracing pipeline, executing
 * the instrumented code in a controlled environment and collecting
 * trace events generated by the Aran advice functions.
 *
 * @example
 * ```typescript
 * const result = record({
 *   instrumented: aranInstrumentedCode,
 *   config: expandedConfig
 * });
 * // result.steps contains the trace events from execution
 * ```
 *
 * @param input - Object containing instrumented code and configuration
 * @returns Object with original inputs plus trace steps and metadata
 * @throws {Error} If instrumented is provided but not a string, or config is not an object
 *
 * @remarks
 * Execution limits are controlled via the config's meta field:
 * - `maxSteps`: Stop after N trace events
 * - `maxMemory`: Stop when trace exceeds N MB
 * - `maxRecursionDepth`: Stop at recursion depth N
 * - `maxExecutionTime`: Stop after N milliseconds
 *
 * When any limit is reached, execution stops gracefully and returns
 * partial trace with metadata indicating which limit was hit.
 *
 * Note: Async/await execution is not supported in v1.0.
 * This feature is planned for v2.0.
 *
 * @since 1.0.0
 */
function record(
  { instrumented, config }: { readonly instrumented?: string; readonly config?: ExpandedConfig } = {},
): RecordOutput {
  if (instrumented !== undefined && typeof instrumented !== 'string') {
    throw new Error(
      'record: expected instrumented to be a string, got ' + typeof instrumented,
    );
  }
  if (
    config !== undefined &&
    (typeof config !== 'object' || config === null || Array.isArray(config))
  ) {
    throw new Error(
      'record: expected config to be an object, got ' +
        (Array.isArray(config) ? 'array' : typeof config),
    );
  }

  const resolvedInstrumented = instrumented ?? '';
  const resolvedConfig = config ?? createConfig({});

  // Stub: one empty object per non-space character
  const count = resolvedInstrumented.split('').filter((c: string) => c !== ' ').length;
  const steps: readonly Step[] = Array.from({ length: count }, () => ({}) as Step);

  return {
    instrumented: resolvedInstrumented,
    config: resolvedConfig,
    steps,
  };
}

export default record;
