/* notes
    !! this trace will require static analysis as well, for example
        to id an initialization with it's declaration, the simplest (I think) appraoch is to statically (via AST node made available in Aran) check if the declaration has an initialization (or vice-versa) and track some state to align ID references.  similar for socpe?
            or is there a way to do this more dynamically? (without managing an entire virtual runtime)

    ideally the trace shouldn't need metadata for processing
        specially relevant for reference tracing config design - if there are more than one format, the consumer will need to know (or detect) which
*/

// should all values be uniformly represented as an object?
const value = {
  ref: null, // if primitive, number otherwise
  value: '...',
  type: 'typeof result',
  instanceof: 'instanceof result'
};

const exampleTrace = [
  // --- bindings examples ---
  // how to handle cross-referencing trace entries when hoisting is involved?
  //    is the declaration listed when its hoisted, not when that line is reached?
  //    then is the declaration/init line treated as an "assign"
  {
    category: 'binding',
    id: 8,
    event: 'declare',
    kind: 'const', // let, var, function, parameter, global,
    scope: 4 // number references scope creation's trace entry ID, if scopes are enabled
  },
  {
    category: 'binding',
    id: 11,
    event: 'initialize',
    value: 'whatever',
    declaration: 8 // number references variable declaration trace entry ID
  },
  {
    category: 'binding',
    id: 11,
    event: 'assign',
    value: 'whatever',
    // do we need this for assignings?
    declaration: 8 // number references variable declaration trace entry ID
  },
  {
    category: 'binding',
    id: 11,
    event: 'read',
    value: 'whatever',
    // do we need this for readings?
    declaration: 8 // number references variable declaration trace entry ID
  },

  // --- references examples ---
  // how exactly to represent? does each nested ref live by id?
  //    or _do_ we log the {id, value} objects recursively?
  //        tedious, but otherwise how to know when a nested object/array is modified?
  // circular is another tricky case
  {
    category: 'reference',
    id: 11,
    event: 'create',
    ref: 1, // the id generated by referenceTracker
    value: '...',
    instanceof: '' // what it's an instance of
  },
  {
    category: 'reference',
    id: 11,
    event: 'access',
    ref: 1, // the id generated by referenceTracker
    value: '...', // if depending on reference.format config
    instanceof: '' // what it's an instance of
  },
  {
    category: 'reference',
    id: 11,
    event: 'mutate',
    ref: 1, // the id generated by referenceTracker
    diff: '...', // if depending on reference.format config
    instanceof: '' // what it's an instance of
  },

  // --- property examples ---
  {
    category: 'property',
    id: 11,
    event: 'create',
    kind: 'literal', // or computed
    key: '',
    value: ''
  },

  // --- expansion examples ---
  {
    category: 'expansions'
  },

  // --- operators examples ---
  {
    category: 'operator'
  },

  // --- parentheses examples ---
  {
    category: 'parenthesis'
  },

  // --- template literal examples ---
  {
    category: 'template'
  },

  // --- symbol examples ---
  {
    category: 'symbol'
  },

  // --- scopes examples ---
  {
    category: 'scope'
  },

  // --- controlFlow examples ---
  {
    category: 'controlFlow'
  },

  // --- errorHandling examples ---
  {
    category: 'errorHandling'
  },

  // --- functions examples ---
  {
    category: 'function'
  },

  // --- classes examples ---
  {
    category: 'class'
  },

  // --- modules examples ---
  {
    category: 'module'
  },

  // --- dynamic examples ---
  {
    category: 'dynamic'
  }
];
